import LocalizedStrings from "react-native-localization";

const StringsOfLanguages = new LocalizedStrings({
  en: {
    loading: "loading",
    Cancel: "cancel",
    Select: "select",
    sorryNo: "Sorry No",
    found: "found",
    User: "User",
    addFoto: "Add foto",
    imageLibrary: "Bildarchiv",
    camera: "Camera",
    employee: "Employee",
    stockEdit:'Stock Edit',
    return:'Return',
    delivery:'Delivery',
    selectEmployee:'Select Employees',
    changePassword: "Change Password",
    resetPassword:'Reset Password',
    logout: "Logout",
    View: "View",
    Orders: "Orders",
    meterNumber: "Meter number",
    reading: "Reading",
    Document: "Document",
    Add: "Add",
    Order: "Order",
    OrderId: "Order-ID",
    Change: "Change",
    sendRestPasswordLink: "Send Password Reset Link",
    Appointment: "Appointment",
    password:'Password',
    taskType: "Task Type",
    task:'Task',
    pleaseEnter:'Please Enter',
    Status: "Status",
    taskText: "Task Text",
    Location: "Location",
    Vehicles: "Vehicles",
    Colleagues: "Colleagues",
    Details: "Details",
    documents: "Documents",
    timeRecord: "Time Record",
    productMask: "Product Mask",
    customOrder: "Custom Order",
    orderCategory: "Order Category",
    startDate: "Aufbau Datum",
    endDate: "End Date",
    Description: "Description",
    Customer: "Customer",
    contactPerson: "Contact Person",
    projectManager: "Project Manager",
    projectManagerPhoneNumber: "Project Manager Phone Number",
    Save: "Save",
    Start: "Start",
    Pause: "Pause",
    Resume: "Resume",
    allOrders:'All Orders',
    addNote: "Add Note",
    stop: "Stop",
    previousTask: "Previous Tasks",
    tasks:'Tasks',
    meterReading:'Meter Reading',
    recordMeterReading:'Record Meter Reading',
    selectOrder:'Select Orders',
    please:'Please',
    oldPassword:'Old Password',
    newPassword:'New Password',
    confirmPassword:'Confirm Passoword',
    dates:'Dates',
    typeToFilterProducts:'Type to filter products',
    category:'Category',
    basicInformation:'Basic Information',
    productMovement:'Product Movement',
    recordTime:'Record Time',
    stockQty:'Stock Qty',
    action:'Action',
    quantity:'Quantity',
    productName:'Product Name',
    date:'Date',
    product:'Product',
    fileName:'File Name',
    changeLanguage:'Change Language',
    forgotPassword: "Forgot Password",
  },
  de: {
    changeLanguage:'Sprache ändern',
    product:'Material',
    fileName:'Dateiname',
    date:'Datum',
    productName:'Name Material',
    quantity:'Menge',
    action:'Aktion',
    stockQty:'Bestand Menge',
    task:'Aufgabe',
    return:'Abbau',
    delivery:'Lieferung',
    loading: "Wird geladen",
    Cancel: "abbrechen",
    Select: "auswählen",
    please:'Bitte',
    password:'Passwort',
    sorryNo: "Entschuldige Nein",
    found: "Gefunden",
    User: "Benutzer",
    addFoto: "Foto hinzufügen",
    imageLibrary: "Image Library",
    camera: "Kamera",
    employee: "Mitarbeiter",
    selectEmployee:'Mitarbeiter auswählen',
    changePassword: "Passwort ändern",
    resetPassword:'Passwort zurücksetzen',
    allOrders:'Aufträge',
    logout: "Logout",
    View: "Anzeigen",
    Orders: "Aufträge",
    meterNumber: "Zählernummer",
    reading: "Zählerstand",
    Document: "Dokument",
    documents: "Unterlagen",
    Add: "hinzufügen",
    Change: "Ändern",
    Order: "Projekt",
    OrderId: "Bestellnummer",
    sendRestPasswordLink: "Passwort Link senden",
    Appointment: "Termin",
    taskType: "Aufgabentyp",
    Status: "Status",
    taskText: "Aufgabe Text",
    Location: "Ort",
    Vehicles: "Fuhrpark",
    Colleagues: "Kollegen",
    Details: "Einzelheiten",
    timeRecord: "Zeiterfassung",
    productMask: "Lieferschein erfassen",
    customOrder: "Individuelles Projekt",
    orderCategory: "Projektkategorie",
    startDate: "Aufbau Datum",
    endDate: "Projektende",
    Description: "Beschreibung",
    Customer: "Kunde",
    contactPerson: "Ansprechpartner",
    projectManager: "Projektleiter",
    projectManagerPhoneNumber: "Projektleiter Telefonnummer",
    Save: "Speichern",
    Start: "Start",
    Pause: "Pause",
    Resume: "Fortsetzen",
    addNote: "Notiz hinzufügen",
    stop: "Halt",
    basicInformation:'Grundinformation',
    forgotPassword: "Passwort vergessen",
    previousTask: "Vorherige Aufgaben",
    tasks:'Aufgaben',
    meterReading:'Zählerstand',
    recordMeterReading:'Zählerstand aufzeichnen',
    selectOrder:'Projekte auswählen',
    oldPassword:'Altes Passwort',
    newPassword:'Neues Passwort',
    confirmPassword:'Passwort bestätigen',
    dates:'Daten',
    typeToFilterProducts:'Tippen um Material zu filtern...',
    category:'Kategorie',
    pleaseEnter:'Bitte eingeben',
    productMovement:'Materialbewegungen',
    recordTime:'Arbeitszeit aufzeichnen',
    stockEdit:'Bestand bearbeiten',
  },

});

export default StringsOfLanguages;
