export const countries = [
  "United Arab Emirates",
  "Argentina",
  "Australia",
  "Brazil",
  "Canada",
  "Liechtenstein",
  "China",
  "Egypt",
  "France",
  "United Kingdom",
  "Hong Kong",
  "Indonesia",
  "Israel",
  "India",
  "Japan",
  "South Korea",
  "Mexico",
  "Qatar",
  "Russian Federation",
  "Saudi Arabia",
  "Sweden",
  "Singapore",
  "Thailand",
  "United States of America",
  "Vietnam",
  "South Africa"
]
