# Generated by Django 2.2.24 on 2021-12-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=250, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_detail', to='booking.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('price_id', models.CharField(max_length=250, null=True)),
                ('subscription_id', models.CharField(max_length=250, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='booking.AppointmentPaymentDetail')),
            ],
        ),
    ]
