# Generated by Django 2.2.24 on 2021-09-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210818_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hear_about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
