# Generated by Django 2.2.24 on 2021-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_paymentdetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='check_list')),
                ('category', models.CharField(choices=[('1', 'Preparing Families Postpartum and Beyond'), ('2', 'Lactation Support'), ('3', 'Mental Health Support'), ('4', 'Resource Hub')], default='1', max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
