# Generated by Django 2.2.24 on 2021-11-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211129_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availability_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
