# Generated by Django 2.2.24 on 2021-12-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_availability_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_expiry',
            field=models.DateTimeField(blank=True, max_length=150, null=True),
        ),
    ]
