# Generated by Django 2.2.25 on 2021-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211209_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_help',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('lactation_support', 'Lactation Support')], default='mental_health', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='product_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
