# Generated by Django 2.2.25 on 2021-12-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211215_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='providers',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='to_date',
        ),
        migrations.AddField(
            model_name='availability',
            name='friday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='monday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='saturday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider_shift', to='users.Shifts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='sunday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='thursday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='tuesday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='wednesday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.TextField(blank=True, help_text='Please Write Specialization in Comma Seprated Format', null=True),
        ),
    ]
