# Generated by Django 2.2.26 on 2022-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220111_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
