# Generated by Django 2.2.26 on 2022-01-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220111_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='client',
        ),
    ]
